### PR TITLE
Match EIPs against DNS names and expose the latter in entity

### PR DESCRIPTION
**Pull request by avaczi**
otherwise the `postgresql_database` entities won't work.  Comes with tests.

### CODE REVIEW

**Comment by mohabusama** [comment]
👍

**Comment by avaczi** [comment]
:+1:

**Comment by mohabusama** [comment]
Please resolve the conflicts - merging master should bring in OpenTracing support.

**Comment by avaczi** [comment]
:+1:

**Comment by avaczi** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Pull request merged**
