### PR TITLE
Fix missing instance entity tags

### LINKED ISSUE #96: Missing instance properties (tags)
Any delay/update of the tags will be missed. Introduced by #95

### PR DESCRIPTION
**Pull request by mohabusama**
Fix #96

### CODE REVIEW

**Comment by Jan-M** [comment]
don't you want to make the intervals configurable now? :D

**Comment by mohabusama** [comment]
@Jan-M let's just prove its usefulness and then we expand 😄

**Comment by Jan-M** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Pull request merged**
