### PR TITLE
Fix entity dict comparison

### LINKED ISSUE #34: Comparing entities fails in certain cases
`json.dumps` with `sort_keys` fails: `TypeError: unorderable types: int() < str()`

### PR DESCRIPTION
**Pull request by mohabusama**
Fix #34

### CODE REVIEW

**Comment by mohabusama** [comment]
👍

**Comment by hjacobs** [comment]
What was wrong with the previous code?

**Comment by hjacobs** [comment]
Ah, sorry, just read #34 :smirk:

**Comment by hjacobs** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Pull request merged**
